export const CLASS_DECORATOR_KEY = 'CLASS:DECORATOR';
export const CONTROLLER_DECORATOR_KEY = 'CONTROLLER_DECORATOR_KEY';
export const INTERCEPTOR_DECORATOR_KEY = 'INTERCEPTOR_DECORATOR_KEY';
export const USE_INTERCEPTOR_DECORATOR_KEY = 'USE_INTERCEPTOR_DECORATOR_KEY';
export const REQUEST_METHOD_DECORATOR_KEY = 'REQUEST_METHOD_DECORATOR_KEY';
export const SERVICE_DECORATOR_KEY = 'SERVICE_DECORATOR_KEY';
export const AUTO_WIRED_DECORATOR_KEY = 'AUTO_WIRED_DECORATOR_KEY';
export const VALUE_DECORATOR_KEY = 'VALUE_DECORATOR_KEY';
